version: '3'
services:
  nginx:
    restart: always
    build:
      context: .docker
      dockerfile: Dockerfile-nginx
    volumes:
      - ./app:/var/www/html/

      - .docker/nginx/test.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    restart: always
    build:
      context: .docker
      dockerfile: Dockerfile-php
    volumes:
      - ./app:/var/www/html/
      - .docker/supervisor/queue_test.conf:/etc/supervisor/conf.d/queue_test.conf:ro

  db_test:
    restart: always
    build:
      context: .docker
      dockerfile: Dockerfile-mariadb
    environment:
      MYSQL_DATABASE: rest_test
      MYSQL_USER: rest_test
      MYSQL_PASSWORD: rest_test
      MYSQL_ROOT_PASSWORD: root

  rabbit_test:
    restart: always
    build:
      context: .docker
      dockerfile: Dockerfile-rabbitmq